In [2]:
import numpy as np
import cv2 

In [9]:
img = cv2.imread('images/1.jpeg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
b,g,r = cv2.split(img)

In [11]:
print(b,g,r)

[[ 86  86  73 ... 192 184 189]
 [ 77  76  76 ... 192 192 194]
 [ 64  77  79 ... 187 188 188]
 ...
 [ 14   3   5 ...   9   3   0]
 [ 21  15  26 ...  24  24  15]
 [ 16  21  29 ...  22  16  22]] [[ 75  75  58 ... 191 184 188]
 [ 65  64  61 ... 188 189 191]
 [ 52  65  63 ... 181 183 183]
 ...
 [ 31  22  28 ...  20  15   9]
 [ 45  42  55 ...  41  43  34]
 [ 51  56  64 ...  45  44  52]] [[ 14  15   2 ... 148 138 143]
 [  6   5   4 ... 145 144 146]
 [  0   7   9 ... 139 138 138]
 ...
 [  8   0   6 ...   7   1   0]
 [ 21  17  30 ...  24  27  17]
 [ 22  27  35 ...  23  21  29]]


In [21]:
img2 = cv2.merge((b,g,r))
cv2.imshow('image',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
temp = img[300:400,400:500]
img[100:200, 200:300] = temp
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [47]:
img1 = cv2.imread('images/1.jpeg')
img2 = cv2.imread('images/2.jpeg')

img1 = cv2.resize(img1,(520,520))
img2 = cv2.resize(img2,(520,520))

In [55]:
dst = cv2.addWeighted(img1,.7,img2,.3,0)
cv2.imshow('image',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()